name: Dependabot PR CI
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  auto-merge:
    name: Merge minor/patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GH_PAT }}
