name: Dependabot PR CI
on:
  pull_request:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  auto-merge:
    name: Merge and label minor/patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: koj-co/dependabot-pr-action@master
        with:
          token: ${{ secrets.GH_PAT }}
          auto-label: true
          merge-minor: true
          merge-patch: true
