name: Deploy CI
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    name: Build and Commit
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache node modules
        uses: c-hive/gha-npm-cache@v1
      - name: Install dependencies
        run: npm ci
      - name: Run build command
        run: npm run build
      - name: Commit build
        uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: ":rocket: Deploy new version [skip ci]"
          commit_user_name: BetaHuhn Bot
          commit_user_email: bot@mxis.ch
          commit_author: BetaHuhn Bot <bot@mxis.ch>
  upload:
    needs: [build]
    name: Upload to CDN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: BetaHuhn/do-spaces-action@master
        with:
          access_key: ${{ secrets.ACCESS_KEY}}
          secret_key: ${{ secrets.SECRET_KEY }}
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
          source: "dist/feedback-js.min.js"
          out_dir: "dist/feedback-js"
          versioning: true